# Generated by Django 4.2.7 on 2023-12-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_musicmodel_publication_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicmodel',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
