# Generated by Django 4.2.7 on 2024-01-02 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0007_albummodel_musicmodel_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='albummodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='albummodel',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
